#!/bin/sh
#
# xwax 'scan' script which generates a series to test the BPM listing; eg.
#
#   xwax -s test-scan-bpm -l /dev/null
#

LOWEST=30.0
HIGHEST=320.0
STEP=0.1

seq "$LOWEST" "$STEP" "$HIGHEST" | awk -- '
	BEGIN {
		OFS="\t"
	}
	{
		print "/dev/null", "BPM test", "Track at " $1 " BPM", $1
	}
'
